<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 2 UN TABLEAU DE DONNEES AGREGEES (Pays d’Europe en 1988) | Premiers pas en statistique avec R</title>
  <meta name="description" content="Exercices commentés pour bien débuter en R." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 2 UN TABLEAU DE DONNEES AGREGEES (Pays d’Europe en 1988) | Premiers pas en statistique avec R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Exercices commentés pour bien débuter en R." />
  <meta name="github-repo" content="ClaudeGrasland/StatR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 2 UN TABLEAU DE DONNEES AGREGEES (Pays d’Europe en 1988) | Premiers pas en statistique avec R" />
  
  <meta name="twitter:description" content="Exercices commentés pour bien débuter en R." />
  

<meta name="author" content="Claude Grasland" />


<meta name="date" content="2019-08-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html">
<link rel="next" href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prérequis</a></li>
<li class="chapter" data-level="2" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><i class="fa fa-check"></i><b>2</b> UN TABLEAU DE DONNEES AGREGEES (Pays d’Europe en 1988)</a><ul>
<li class="chapter" data-level="2.1" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#definition-de-lenvironnement-de-travail"><i class="fa fa-check"></i><b>2.1</b> Définition de l’environnement de travail</a><ul>
<li class="chapter" data-level="2.1.1" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#charger-ou-installer-les-packages-utiles."><i class="fa fa-check"></i><b>2.1.1</b> charger ou installer les packages utiles.</a></li>
<li class="chapter" data-level="2.1.2" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#definir-un-espace-de-travail"><i class="fa fa-check"></i><b>2.1.2</b> Définir un espace de travail</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#charger-un-tableau-de-donnees"><i class="fa fa-check"></i><b>2.2</b> Charger un tableau de données</a><ul>
<li class="chapter" data-level="2.2.1" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#importation-dun-tableau"><i class="fa fa-check"></i><b>2.2.1</b> Importation d’un tableau</a></li>
<li class="chapter" data-level="2.2.2" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#choix-du-nom-des-lignes"><i class="fa fa-check"></i><b>2.2.2</b> Choix du nom des lignes</a></li>
<li class="chapter" data-level="2.2.3" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#verification-du-type-des-variables"><i class="fa fa-check"></i><b>2.2.3</b> Vérification du type des variables</a></li>
<li class="chapter" data-level="2.2.4" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#enregistrement-du-tableau-au-format-propre-a-r"><i class="fa fa-check"></i><b>2.2.4</b> Enregistrement du tableau au format propre à R</a></li>
<li class="chapter" data-level="2.2.5" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#un-petit-resume-statistique"><i class="fa fa-check"></i><b>2.2.5</b> Un petit résumé statistique</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#analyse-1-y-quanti-x-quali"><i class="fa fa-check"></i><b>2.3</b> ANALYSE 1 (Y Quanti / X Quali)</a><ul>
<li class="chapter" data-level="2.3.1" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#analyse-de-la-repartition-des-pays-par-bloc-politique-bloc"><i class="fa fa-check"></i><b>2.3.1</b> Analyse de la répartition des pays par bloc politique (BLOC)</a></li>
<li class="chapter" data-level="2.3.2" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#analyse-de-la-distribution-des-taux-de-mortalite-infantile-tmi"><i class="fa fa-check"></i><b>2.3.2</b> Analyse de la distribution des taux de mortalité infantile (TMI)</a></li>
<li class="chapter" data-level="2.3.3" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#comaparaison-de-la-mortalite-infantile-par-bloc-bloctmi"><i class="fa fa-check"></i><b>2.3.3</b> Comaparaison de la mortalité infantile par bloc (BLOC*TMI)</a></li>
<li class="chapter" data-level="2.3.4" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#test-degalite-des-moyennes-bloctmi"><i class="fa fa-check"></i><b>2.3.4</b> Test d’égalité des moyennes (BLOC*TMI)</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#analyse-2-y-quanti-x-quanti"><i class="fa fa-check"></i><b>2.4</b> ANALYSE 2 (Y Quanti / X Quanti)</a><ul>
<li class="chapter" data-level="2.4.1" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#extraction-dune-matrice-a-partir-dun-tableau"><i class="fa fa-check"></i><b>2.4.1</b> Extraction d’une matrice à partir d’un tableau</a></li>
<li class="chapter" data-level="2.4.2" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#calcul-des-correlations"><i class="fa fa-check"></i><b>2.4.2</b> Calcul des corrélations</a></li>
<li class="chapter" data-level="2.4.3" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#visualisation-de-la-forme-de-la-relation-entre-deux-variables-quantitatives"><i class="fa fa-check"></i><b>2.4.3</b> Visualisation de la forme de la relation entre deux variables quantitatives</a></li>
<li class="chapter" data-level="2.4.4" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#un-premier-modele-de-regression-lineaire-quick-dirty"><i class="fa fa-check"></i><b>2.4.4</b> Un premier modèle de régression linéaire (quick &amp; dirty …)</a></li>
<li class="chapter" data-level="2.4.5" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#un-deuxieme-modele-plus-satisfaisant-sur-le-plan-statistique-et-theorique"><i class="fa fa-check"></i><b>2.4.5</b> Un deuxième modèle plus satisfaisant sur le plan statistique et théorique</a></li>
<li class="chapter" data-level="2.4.6" data-path="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html"><a href="un-tableau-de-donnees-agregees-pays-deurope-en-1988.html#un-troisieme-modele-la-revanche-des-pays-socialistes"><i class="fa fa-check"></i><b>2.4.6</b> Un troisième modèle : la revanche des pays socialistes …</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><i class="fa fa-check"></i><b>3</b> UN TABLEAU DE DONNES D’ENQUETE (Les ménages de Yemessoa en 2005)</a><ul>
<li class="chapter" data-level="3.1" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#definition-de-lenvironnement-de-travail-1"><i class="fa fa-check"></i><b>3.1</b> Définition de l’environnement de travail</a><ul>
<li class="chapter" data-level="3.1.1" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#charger-ou-installer-les-packages-utiles.-1"><i class="fa fa-check"></i><b>3.1.1</b> charger ou installer les packages utiles.</a></li>
<li class="chapter" data-level="3.1.2" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#definir-un-espace-de-travail-1"><i class="fa fa-check"></i><b>3.1.2</b> Définir un espace de travail</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#charger-un-tableau-de-donnees-1"><i class="fa fa-check"></i><b>3.2</b> Charger un tableau de données</a><ul>
<li class="chapter" data-level="3.2.1" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#importation-dun-tableau-1"><i class="fa fa-check"></i><b>3.2.1</b> Importation d’un tableau</a></li>
<li class="chapter" data-level="3.2.2" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#verification-du-type-des-variables-1"><i class="fa fa-check"></i><b>3.2.2</b> Vérification du type des variables</a></li>
<li class="chapter" data-level="3.2.3" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#un-petit-resume-statistique-1"><i class="fa fa-check"></i><b>3.2.3</b> Un petit résumé statistique</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#analyse-3-y-quali-x-quali"><i class="fa fa-check"></i><b>3.3</b> ANALYSE 3 (Y Quali/ X Quali)</a><ul>
<li class="chapter" data-level="3.3.1" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#analyse-de-la-variable-dependante-y"><i class="fa fa-check"></i><b>3.3.1</b> Analyse de la variable dépendante (Y)</a></li>
<li class="chapter" data-level="3.3.2" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#analyse-de-la-variable-independante-x"><i class="fa fa-check"></i><b>3.3.2</b> Analyse de la variable indépendante (X)</a></li>
<li class="chapter" data-level="3.3.3" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#visualisation-de-la-distribution-croisee-de-y-et-x"><i class="fa fa-check"></i><b>3.3.3</b> Visualisation de la distribution croisée de Y et X</a></li>
<li class="chapter" data-level="3.3.4" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#calcul-du-tableau-de-contingence-et-des-trois-tableaux-de-pourcentage-associes"><i class="fa fa-check"></i><b>3.3.4</b> Calcul du tableau de contingence et des trois tableaux de pourcentage associés</a></li>
<li class="chapter" data-level="3.3.5" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#calcul-du-tableau-theorique-et-test-du-chi-2"><i class="fa fa-check"></i><b>3.3.5</b> Calcul du tableau théorique et test du chi-2</a></li>
<li class="chapter" data-level="3.3.6" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#une-jolie-figure-pour-interpreter-la-relation-si-elle-est-significative"><i class="fa fa-check"></i><b>3.3.6</b> Une jolie figure pour interpréter la relation (si elle est significative)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html"><a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html#a-vous-de-jouer"><i class="fa fa-check"></i><b>3.4</b> A VOUS DE JOUER !</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Premiers pas en statistique avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="un-tableau-de-donnees-agregees-pays-deurope-en-1988" class="section level1">
<h1><span class="header-section-number">Chapitre 2</span> UN TABLEAU DE DONNEES AGREGEES (Pays d’Europe en 1988)</h1>
<p>Accrochez vos ceintures … on plonge directement dans un programme R qu’il s’agit juste d’exécuter sans comprendre ce qui se passe pour avoir une idée des possibilités du logiciel mais aussi des difficultés. Vous êtes un peu comme un étranger qui entend parler une langue nouvelle et découvre de nouveaux mots et essaye de les reproduire comme dans la méthode Assimil … Evidemment ça ne marche pas à tous les coups.</p>
<p>On commence ici par un exemple où tout se passe bien et on utilise pour cela un exemple fétiche de l’enseignant, celui des pays d’Europe en 1988 à la veille de la chute du mur de Berlin. Exemple qui a été testé depuis 30 ans sur tous les logiciels de statistique possible (Lotus, Calc, SAS, XLSTAT, SPAD, ….). Il vous est recommandé d’avoir également un exemple fétiche sur lequel vous pourrez tester à votre tour le programme ci-dessous en l’adaptant.</p>
<p>Les 24 pays d’Europe sont identifiés par leur code iso (PAYS), leur appartenance aux pays socialistes ou capitalistes (BLOC), leur position spatiale (X,Y) et tout un ensemble de variables économpiques et sociale telles que le PNB par habitant (PNB), le taux de mortlaité infantile (TMI), l’espérance de vie à la naissance (ESP), le taux d’urbanisation (URB), le taux de natalité (NAT), le taux de mortalité (MOR), l’indice conjoncturel de fécondité (FEC), le % de jeunes de 0-14 ans (JEU), le * de vieux de 65 ans et plus (VIE), la superficie totale en milliers de kM2 (SUP) et la population totale en millions (POP).</p>
<div id="definition-de-lenvironnement-de-travail" class="section level2">
<h2><span class="header-section-number">2.1</span> Définition de l’environnement de travail</h2>
<div id="charger-ou-installer-les-packages-utiles." class="section level3">
<h3><span class="header-section-number">2.1.1</span> charger ou installer les packages utiles.</h3>
<p>Au début de chaque programme R, on commence par indiquer la liste de tous les packages dont on aura besoin pour executer les traitements. On les charge par la commande <em>library(nom_du_package)</em>. ici, on va juste installe le package <em>Hmisc</em> qui regroupe un grand nombre d’outils statistiques courants.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(Hmisc)</a></code></pre></div>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre><code>## Loading required package: Formula</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## 
## Attaching package: &#39;Hmisc&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     format.pval, units</code></pre>
<p>Si un message d’erreur apparaît, c’est qu’il faut installer le package à partir d’internet. On le fait avec le menu <strong>Tools/install Package</strong></p>
</div>
<div id="definir-un-espace-de-travail" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Définir un espace de travail</h3>
<p>le répertoire de travail dans lequel seront lus ou écrit les fichiers.</p>
<p>Dans le programme ci-dessous, les lignes commençant par “#” sont des commentaires. La seule ligne active est getwd() qui indique la position du répertoire courant. Il est recommandé aux débutants, mais aussi aux programmeurs plus expérimentés de napas hésiter à ajouter beaucoup de lignes de commentaires. Cela facilité l’apprentissage et permet de transmettre ses programmes à d’autres.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="co"># ---------------------------</span></a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="co"># (1) ESPACE DE TRAVAIL</span></a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="co"># ---------------------------</span></a>
<a class="sourceLine" id="cb8-4" data-line-number="4"><span class="co"># (1.1) Quel est le répertoire actuel ?</span></a>
<a class="sourceLine" id="cb8-5" data-line-number="5"><span class="kw">getwd</span>()</a></code></pre></div>
<pre><code>## [1] &quot;/Users/claudegrasland1/git/StatR&quot;</code></pre>
<p>On repère ensuite le chemin de l’emplacement du dossier où se trouvent les données et on examine son contenu. Attention, contrairement à windows il faut toujours utiliser des slash (/) et non pas des antislash pour décrire les chemins d’accès des fichiers</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="co"># (1.2) Choix du rÈpertoire contenant les donnÈes</span></a>
<a class="sourceLine" id="cb10-2" data-line-number="2">monchemin&lt;-<span class="st">&quot;data/euro1988&quot;</span></a>
<a class="sourceLine" id="cb10-3" data-line-number="3"><span class="kw">list.files</span>(monchemin)</a></code></pre></div>
<pre><code>## [1] &quot;euro1988.rda&quot; &quot;euro1988.txt&quot;</code></pre>
<p>Nous allons maintenant essayer de charger le fichier de données</p>
</div>
</div>
<div id="charger-un-tableau-de-donnees" class="section level2">
<h2><span class="header-section-number">2.2</span> Charger un tableau de données</h2>
<p>On utilise ici une procédure adaptée à la lecture de fichiers texte : <em>read.table()</em>
L’instruction <em>header=TRUE</em> signale que la première ligne donne le nom des variables
L’instruction <em>dec=“.”</em> signale que les décimales sont représentées par des points et non pas des virgules.</p>
<div id="importation-dun-tableau" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Importation d’un tableau</h3>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="co"># --------------------------------------------------------</span></a>
<a class="sourceLine" id="cb12-2" data-line-number="2"><span class="co"># (2) IMPORTATION ET MISE EN FORME D&#39;UN TABLEAU DE DONNEES</span></a>
<a class="sourceLine" id="cb12-3" data-line-number="3"><span class="co"># --------------------------------------------------------</span></a>
<a class="sourceLine" id="cb12-4" data-line-number="4"><span class="co"># (2.1) Importation d&#39;un fichier .txt</span></a>
<a class="sourceLine" id="cb12-5" data-line-number="5">euro &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;data/euro1988/euro1988.txt&quot;</span>, </a>
<a class="sourceLine" id="cb12-6" data-line-number="6">                   <span class="dt">dec=</span><span class="st">&quot;.&quot;</span>,</a>
<a class="sourceLine" id="cb12-7" data-line-number="7">                   <span class="dt">header=</span><span class="ot">TRUE</span>)</a></code></pre></div>
<p>Pour savoir si le chargement s’est bien pssé on peut afficher le tableau en tapant son nom</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">euro </a></code></pre></div>
<pre><code>##    PAYS BLOC   PNB  TMI ESP URB NAT MOR FEC JEU VIE SUP  POP    X    Y
## 1   ALB  Soc   600 43.0  71  34  27   6 3.3  35   5  29  3.1 1445  684
## 2   AUT  Cap 10000 10.3  75  55  12  12 1.4  18  14  84  7.6 1121 1031
## 3   BEL  Cap  9200  9.7  75  95  12  11 1.5  19  14  31  9.9  734 1187
## 4   BUL  Soc  2000 14.5  72  65  13  11 2.0  21  11 111  9.0 1649  839
## 5   DAN  Cap 12600  8.4  75  84  11  11 1.5  18  15  43  5.1  887 1500
## 6   ESP  Cap  4800  9.0  76  91  12   8 1.7  23  12 505 39.0  358  582
## 7   FIN  Cap 12200  5.8  74  62  12  10 1.6  19  13 337  4.9 1299 2103
## 8   FRA  Cap 10100  8.0  75  73  14  10 1.8  21  13 551 55.9  646  941
## 9   GRE  Cap  3700 12.3  74  58  11   9 1.7  21  13 132 10.1 1453  593
## 10  HON  Soc  2000 19.0  70  58  12  14 1.8  21  13  93 10.6 1341 1042
## 11  IRL  Cap  5100  8.7  73  56  17  10 2.4  29  11  70  3.5  275 1373
## 12  ITA  Cap  8600 10.1  75  72  10  10 1.4  19  13 301 57.3 1076  773
## 13  NOR  Cap 15500  8.5  76  71  13  11 1.7  19  16 324  4.2  939 1995
## 14  PAY  Cap 10000  7.7  76  89  13   9 1.6  19  12  34 14.7  769 1286
## 15  POL  Soc  2100 17.5  71  61  17  10 2.2  26   9 313 38.0 1279 1339
## 16  POR  Cap  2200 15.8  73  30  12   9 1.7  23  12  92 10.3  147  567
## 17  RDA  Soc  3700  9.2  72  77  13  13 1.7  19  14 108 16.6 1023 1302
## 18  RFA  Cap 12000  8.6  75  94  10  11 1.4  15  15 248 61.2  918 1188
## 19  ROU  Soc  1200 25.6  70  49  16  11 2.3  25   9 238 23.0 1587 1017
## 20  ROY  Cap  8900  9.5  75  91  13  12 1.8  19  15 245 57.1  336 1452
## 21  SUE  Cap 13200  5.9  77  83  12  11 1.8  18  18 450  8.4 1061 1931
## 22  SUI  Cap 17800  6.8  77  61  12   9 1.5  17  14  41  6.6  882  956
## 23  TCH  Soc  3200 13.9  71  74  14  12 2.0  24  11 128 15.6 1219 1157
## 24  YOU  Soc  2300 27.1  70  47  15   8 2.1  24   8 256 23.6 1356  855</code></pre>
<p>Mais on peut aussi se contenter d’afficher les premières lignes (<em>head</em>) ou les dernières lignes (<em>tail</em>) du tableau. Par exemple, pour voir les trois premières et les 5 dernières lignes :</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">head</span>(euro,<span class="dv">3</span>)</a></code></pre></div>
<pre><code>##   PAYS BLOC   PNB  TMI ESP URB NAT MOR FEC JEU VIE SUP POP    X    Y
## 1  ALB  Soc   600 43.0  71  34  27   6 3.3  35   5  29 3.1 1445  684
## 2  AUT  Cap 10000 10.3  75  55  12  12 1.4  18  14  84 7.6 1121 1031
## 3  BEL  Cap  9200  9.7  75  95  12  11 1.5  19  14  31 9.9  734 1187</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">tail</span>(euro,<span class="dv">5</span>)</a></code></pre></div>
<pre><code>##    PAYS BLOC   PNB  TMI ESP URB NAT MOR FEC JEU VIE SUP  POP    X    Y
## 20  ROY  Cap  8900  9.5  75  91  13  12 1.8  19  15 245 57.1  336 1452
## 21  SUE  Cap 13200  5.9  77  83  12  11 1.8  18  18 450  8.4 1061 1931
## 22  SUI  Cap 17800  6.8  77  61  12   9 1.5  17  14  41  6.6  882  956
## 23  TCH  Soc  3200 13.9  71  74  14  12 2.0  24  11 128 15.6 1219 1157
## 24  YOU  Soc  2300 27.1  70  47  15   8 2.1  24   8 256 23.6 1356  855</code></pre>
<p>Naturellement … les instructions présentées ci-dessus ne marcheront pas pour tous les tableaux et vous devez vous attendre à pas mal de difficultés à ce stade. Il existe en effet beaucoup d’options à connaître pour charger les fichiers. Vous pouvez ainsi examiner toutes les options de la procédure <em>read.table</em> en tapant un ? suivi du nom de la procédure. Et vous pouvez faire de même pour les autres procédures d’importation comme <em>read.csv</em>, <em>read.delim</em>, etc…</p>
</div>
<div id="choix-du-nom-des-lignes" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Choix du nom des lignes</h3>
<p>Par défaut, le nom des lignes correspond à l’ordre de lecture du fichier (<em>1..24</em>). Mais il peut être intéressant de le préciser en lui attribuant par exemple la valeur d’une variable servant d’identifiant.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">rownames</span>(euro)&lt;-euro<span class="op">$</span>PAYS</a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="kw">head</span>(euro)</a></code></pre></div>
<pre><code>##     PAYS BLOC   PNB  TMI ESP URB NAT MOR FEC JEU VIE SUP  POP    X    Y
## ALB  ALB  Soc   600 43.0  71  34  27   6 3.3  35   5  29  3.1 1445  684
## AUT  AUT  Cap 10000 10.3  75  55  12  12 1.4  18  14  84  7.6 1121 1031
## BEL  BEL  Cap  9200  9.7  75  95  12  11 1.5  19  14  31  9.9  734 1187
## BUL  BUL  Soc  2000 14.5  72  65  13  11 2.0  21  11 111  9.0 1649  839
## DAN  DAN  Cap 12600  8.4  75  84  11  11 1.5  18  15  43  5.1  887 1500
## ESP  ESP  Cap  4800  9.0  76  91  12   8 1.7  23  12 505 39.0  358  582</code></pre>
</div>
<div id="verification-du-type-des-variables" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Vérification du type des variables</h3>
<p>On peut s’éviter beaucoup d’ennuis en contrôlant le type des variables qui a été attribué aux différentes colonnes par R lors de la lecture d’un fichier. Pour cela on commence par regarder quels sont les types de variables du tableau à l’aide de l’instruction <em>str()</em> :</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">str</span>(euro)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    24 obs. of  15 variables:
##  $ PAYS: Factor w/ 24 levels &quot;ALB&quot;,&quot;AUT&quot;,&quot;BEL&quot;,..: 1 2 3 4 5 6 7 8 9 10 ...
##  $ BLOC: Factor w/ 2 levels &quot;Cap&quot;,&quot;Soc&quot;: 2 1 1 2 1 1 1 1 1 2 ...
##  $ PNB : int  600 10000 9200 2000 12600 4800 12200 10100 3700 2000 ...
##  $ TMI : num  43 10.3 9.7 14.5 8.4 9 5.8 8 12.3 19 ...
##  $ ESP : int  71 75 75 72 75 76 74 75 74 70 ...
##  $ URB : int  34 55 95 65 84 91 62 73 58 58 ...
##  $ NAT : int  27 12 12 13 11 12 12 14 11 12 ...
##  $ MOR : int  6 12 11 11 11 8 10 10 9 14 ...
##  $ FEC : num  3.3 1.4 1.5 2 1.5 1.7 1.6 1.8 1.7 1.8 ...
##  $ JEU : int  35 18 19 21 18 23 19 21 21 21 ...
##  $ VIE : int  5 14 14 11 15 12 13 13 13 13 ...
##  $ SUP : int  29 84 31 111 43 505 337 551 132 93 ...
##  $ POP : num  3.1 7.6 9.9 9 5.1 39 4.9 55.9 10.1 10.6 ...
##  $ X   : int  1445 1121 734 1649 887 358 1299 646 1453 1341 ...
##  $ Y   : int  684 1031 1187 839 1500 582 2103 941 593 1042 ...</code></pre>
<p>L’instruction <em>str()</em> est très importante dans R. Elle permet en effet d’examiner le type d’un objet et des éléments qui le composent. Ici on note que l’objet euro est un <em>data.frame</em> c’est-à-dire un tableau de données croisant des indivdus (lignes) et des variables de types différents (colonnes). Par défaut, R a attribué le type “Factor” à toutes les variables composées de texte, le type “int” ou integer à toutes les variables comportant uniquement des nombres entiers et enfin le type “num” ou numérique à toutes les variables comportant des chiffres avec des décimales. Il peut arriver que ce choix par défaut ne correspondent pas aux traitements que l’on veut effectuer et, dans ce cas, on procèdera à des conversions de variables d’un type à un autre.</p>
<p>Ainsi le type “Factor” est difficile à utiliser pour les débutants et il est souvent confondu avec le type “Character”. Pour fixer les idées, on peut dire qu’un “Factor” correspond à ces classes portant à la fois un numéro et une étiquette. Ainsi la variable “BLOC” est bien un facteur correspondant à deux classes : celle des pays capitalistes (numéro = 1, étiquette =“cap”) et celle des pays socialistes (numero = 2, étiquette = “soc”). Par contre la variable PAYS ne définit pas des classes puisqu’elle est différente pour chaque pays et est donc du type “character”.</p>
<p>De la même manière, un nombre entier peut conduire à des comportements bizarre pour les valeurs élevées et il vaut mieux utiliser le tupe numérique lorsqu’on est en présence de nombre réels qui ont juste été arrondis à zéro chiffres après la virgule. Dans notre exemple, il n’existe pas de variables entières mais uniquement des nombres réels arrondis.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">euro<span class="op">$</span>PAYS&lt;-<span class="kw">as.character</span>(euro<span class="op">$</span>PAYS)</a>
<a class="sourceLine" id="cb23-2" data-line-number="2">euro<span class="op">$</span>BLOC&lt;-<span class="kw">as.factor</span>(euro<span class="op">$</span>BLOC)</a>
<a class="sourceLine" id="cb23-3" data-line-number="3">euro<span class="op">$</span>PNB&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>PNB)</a>
<a class="sourceLine" id="cb23-4" data-line-number="4">euro<span class="op">$</span>ESP&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>ESP)</a>
<a class="sourceLine" id="cb23-5" data-line-number="5">euro<span class="op">$</span>URB&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>URB)</a>
<a class="sourceLine" id="cb23-6" data-line-number="6">euro<span class="op">$</span>NAT&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>NAT)</a>
<a class="sourceLine" id="cb23-7" data-line-number="7">euro<span class="op">$</span>MOR&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>MOR)</a>
<a class="sourceLine" id="cb23-8" data-line-number="8">euro<span class="op">$</span>JEU&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>JEU)</a>
<a class="sourceLine" id="cb23-9" data-line-number="9">euro<span class="op">$</span>VIE&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>VIE)</a>
<a class="sourceLine" id="cb23-10" data-line-number="10">euro<span class="op">$</span>SUP&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>SUP)</a>
<a class="sourceLine" id="cb23-11" data-line-number="11">euro<span class="op">$</span>POP&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>POP)</a>
<a class="sourceLine" id="cb23-12" data-line-number="12">euro<span class="op">$</span>X&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>X)</a>
<a class="sourceLine" id="cb23-13" data-line-number="13">euro<span class="op">$</span>Y&lt;-<span class="kw">as.numeric</span>(euro<span class="op">$</span>Y)</a>
<a class="sourceLine" id="cb23-14" data-line-number="14"><span class="kw">str</span>(euro)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    24 obs. of  15 variables:
##  $ PAYS: chr  &quot;ALB&quot; &quot;AUT&quot; &quot;BEL&quot; &quot;BUL&quot; ...
##  $ BLOC: Factor w/ 2 levels &quot;Cap&quot;,&quot;Soc&quot;: 2 1 1 2 1 1 1 1 1 2 ...
##  $ PNB : num  600 10000 9200 2000 12600 4800 12200 10100 3700 2000 ...
##  $ TMI : num  43 10.3 9.7 14.5 8.4 9 5.8 8 12.3 19 ...
##  $ ESP : num  71 75 75 72 75 76 74 75 74 70 ...
##  $ URB : num  34 55 95 65 84 91 62 73 58 58 ...
##  $ NAT : num  27 12 12 13 11 12 12 14 11 12 ...
##  $ MOR : num  6 12 11 11 11 8 10 10 9 14 ...
##  $ FEC : num  3.3 1.4 1.5 2 1.5 1.7 1.6 1.8 1.7 1.8 ...
##  $ JEU : num  35 18 19 21 18 23 19 21 21 21 ...
##  $ VIE : num  5 14 14 11 15 12 13 13 13 13 ...
##  $ SUP : num  29 84 31 111 43 505 337 551 132 93 ...
##  $ POP : num  3.1 7.6 9.9 9 5.1 39 4.9 55.9 10.1 10.6 ...
##  $ X   : num  1445 1121 734 1649 887 ...
##  $ Y   : num  684 1031 1187 839 1500 ...</code></pre>
<p>Et voilà : désormais notre tableau ne comporte plus que des variables de type caractère ou de type numérique. Cela nous a demandé un peu de temps mais nous évitera par la suite beaucoup d’ennuis. En effet, <strong>au moins 50 % des erreurs dans R viennent d’un problème de mauvaise définiton du type d’’un objet ou du type d’une variable !!!</strong></p>
</div>
<div id="enregistrement-du-tableau-au-format-propre-a-r" class="section level3">
<h3><span class="header-section-number">2.2.4</span> Enregistrement du tableau au format propre à R</h3>
<p>Il n’est pas forcément necessaire d’enregistrer ses données au format propre à R (<em>.rda</em>)s’il s’agit d’un petit tableau. Il suffit en effet de sauvegarder le programme que nous venons d’écrire et de l’executer chaque fois que nécessaire. Toutefois, il peut arriver que cette étape soit longue et dans ce cas la sauvegarde est utile.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw">save</span>(euro, <span class="dt">file=</span><span class="st">&quot;data/euro1988/euro1988.rda&quot;</span>)</a></code></pre></div>
<p>on pourra ensuite facilement récupérer les données par la commande suivante</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw">load</span>(<span class="st">&quot;data/euro1988/euro1988.rda&quot;</span>)</a></code></pre></div>
</div>
<div id="un-petit-resume-statistique" class="section level3">
<h3><span class="header-section-number">2.2.5</span> Un petit résumé statistique</h3>
<p>N’oublions pas que R est avant tout un logiciel de statistiques… La récompense d’une bonne définition du tableau sera d’obtenir pour chaque variable un résumé adapté à son type :</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="kw">summary</span>(euro)</a></code></pre></div>
<pre><code>##      PAYS            BLOC         PNB             TMI        
##  Length:24          Cap:16   Min.   :  600   Min.   : 5.800  
##  Class :character   Soc: 8   1st Qu.: 2275   1st Qu.: 8.475  
##  Mode  :character            Median : 6850   Median : 9.600  
##                              Mean   : 7208   Mean   :13.121  
##                              3rd Qu.:10575   3rd Qu.:14.825  
##                              Max.   :17800   Max.   :43.000  
##       ESP             URB             NAT             MOR       
##  Min.   :70.00   Min.   :30.00   Min.   :10.00   Min.   : 6.00  
##  1st Qu.:71.75   1st Qu.:57.50   1st Qu.:12.00   1st Qu.: 9.00  
##  Median :74.50   Median :68.00   Median :12.50   Median :10.50  
##  Mean   :73.67   Mean   :67.92   Mean   :13.46   Mean   :10.33  
##  3rd Qu.:75.00   3rd Qu.:83.25   3rd Qu.:14.00   3rd Qu.:11.00  
##  Max.   :77.00   Max.   :95.00   Max.   :27.00   Max.   :14.00  
##       FEC             JEU             VIE            SUP       
##  Min.   :1.400   Min.   :15.00   Min.   : 5.0   Min.   : 29.0  
##  1st Qu.:1.575   1st Qu.:19.00   1st Qu.:11.0   1st Qu.: 80.5  
##  Median :1.700   Median :20.00   Median :13.0   Median :130.0  
##  Mean   :1.829   Mean   :21.33   Mean   :12.5   Mean   :198.5  
##  3rd Qu.:2.000   3rd Qu.:23.25   3rd Qu.:14.0   3rd Qu.:304.0  
##  Max.   :3.300   Max.   :35.00   Max.   :18.0   Max.   :551.0  
##       POP              X                Y       
##  Min.   : 3.10   Min.   : 147.0   Min.   : 567  
##  1st Qu.: 7.35   1st Qu.: 760.2   1st Qu.: 851  
##  Median :10.45   Median :1042.0   Median :1100  
##  Mean   :20.64   Mean   : 991.7   Mean   :1154  
##  3rd Qu.:27.20   3rd Qu.:1309.5   3rd Qu.:1348  
##  Max.   :61.20   Max.   :1649.0   Max.   :2103</code></pre>
<p>On va tenter de répondre à des questions simples sans détailler dans l’immédiat les outils statistiques qui permettent de valider scientifiquement les réponses. On insistera plus ici sur les capacités de visualisation de résultats sous R.</p>
</div>
</div>
<div id="analyse-1-y-quanti-x-quali" class="section level2">
<h2><span class="header-section-number">2.3</span> ANALYSE 1 (Y Quanti / X Quali)</h2>
<p>La mortalité infantile (Y) est-elle significativement plus forte dans les pays socialistes (X)?</p>
<p>Notre objectif est plus généralement de mettre en relation une variable numérique (TMI) avec une variable de type facteur (BLOC). On va procéder par étape en étudiant d’abord chque variable séparément puis en les croisant et finalement en testant notre hypothèse d’une surmortalité infantile des pays socialistes.</p>
<div id="analyse-de-la-repartition-des-pays-par-bloc-politique-bloc" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Analyse de la répartition des pays par bloc politique (BLOC)</h3>
<p>Deux petites commandes pour dénombrer l’effectif des classes et les représenter</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="co"># Analyse de la  variable qualitative (BLOC)</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="co">#calcul des fréquences</span></a>
<a class="sourceLine" id="cb29-3" data-line-number="3"><span class="kw">summary</span>(euro<span class="op">$</span>BLOC)</a></code></pre></div>
<pre><code>## Cap Soc 
##  16   8</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="co">#diagramme en bâtons</span></a>
<a class="sourceLine" id="cb31-2" data-line-number="2"><span class="kw">plot</span>(euro<span class="op">$</span>BLOC)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="analyse-de-la-distribution-des-taux-de-mortalite-infantile-tmi" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Analyse de la distribution des taux de mortalité infantile (TMI)</h3>
<p>Quelques petites commandes pour camlculer les paramètres principaux de la mortalité infantile et la représenter.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="co"># Analyse de la variable quantitative (TMI)</span></a>
<a class="sourceLine" id="cb32-2" data-line-number="2"></a>
<a class="sourceLine" id="cb32-3" data-line-number="3"><span class="co"># calcul et visualisation des quantiles</span></a>
<a class="sourceLine" id="cb32-4" data-line-number="4"><span class="kw">summary</span>(euro<span class="op">$</span>TMI)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   5.800   8.475   9.600  13.121  14.825  43.000</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="kw">boxplot</span>(euro<span class="op">$</span>TMI)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="co">#calcul de la moyenne et de l&#39;écart type</span></a>
<a class="sourceLine" id="cb35-2" data-line-number="2"><span class="kw">mean</span>(euro<span class="op">$</span>TMI)</a></code></pre></div>
<pre><code>## [1] 13.12083</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1"><span class="kw">sd</span>(euro<span class="op">$</span>TMI)</a></code></pre></div>
<pre><code>## [1] 8.513875</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1"><span class="co"># visualisation de l&#39;histogramme</span></a>
<a class="sourceLine" id="cb39-2" data-line-number="2"><span class="kw">hist</span>(euro<span class="op">$</span>TMI)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
</div>
<div id="comaparaison-de-la-mortalite-infantile-par-bloc-bloctmi" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Comaparaison de la mortalité infantile par bloc (BLOC*TMI)</h3>
<p>Quelques outils pour analyser conjointement les deux distributions.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="co"># calcul et visualisation des quantiles</span></a>
<a class="sourceLine" id="cb40-2" data-line-number="2"><span class="kw">tapply</span>(euro<span class="op">$</span>TMI, euro<span class="op">$</span>BLOC, summary)</a></code></pre></div>
<pre><code>## $Cap
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   5.800   7.925   8.650   9.069   9.800  15.800 
## 
## $Soc
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    9.20   14.35   18.25   21.23   25.98   43.00</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw">boxplot</span>(euro<span class="op">$</span>TMI<span class="op">~</span>euro<span class="op">$</span>BLOC)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1"><span class="co">#calcul de la moyenne et de l&#39;écart type</span></a>
<a class="sourceLine" id="cb43-2" data-line-number="2"><span class="kw">tapply</span>(euro<span class="op">$</span>TMI, euro<span class="op">$</span>BLOC, mean)</a></code></pre></div>
<pre><code>##      Cap      Soc 
##  9.06875 21.22500</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1"><span class="kw">tapply</span>(euro<span class="op">$</span>TMI, euro<span class="op">$</span>BLOC, sd)</a></code></pre></div>
<pre><code>##       Cap       Soc 
##  2.434945 10.624197</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1"><span class="co"># visualisation des deux histogrammes</span></a>
<a class="sourceLine" id="cb47-2" data-line-number="2"><span class="kw">par</span>(<span class="dt">mfrow=</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>)) </a>
<a class="sourceLine" id="cb47-3" data-line-number="3"><span class="kw">hist</span>(euro<span class="op">$</span>TMI[euro<span class="op">$</span>BLOC <span class="op">==</span><span class="st">&quot;Soc&quot;</span>],</a>
<a class="sourceLine" id="cb47-4" data-line-number="4"><span class="co">#     xlim = c(0,50),</span></a>
<a class="sourceLine" id="cb47-5" data-line-number="5">     <span class="dt">main=</span><span class="st">&quot;Pays Socialistes&quot;</span>, </a>
<a class="sourceLine" id="cb47-6" data-line-number="6">     <span class="dt">col=</span><span class="st">&quot;red&quot;</span>) </a>
<a class="sourceLine" id="cb47-7" data-line-number="7"><span class="kw">hist</span>(euro<span class="op">$</span>TMI[euro<span class="op">$</span>BLOC <span class="op">==</span><span class="st">&quot;Cap&quot;</span>],</a>
<a class="sourceLine" id="cb47-8" data-line-number="8"><span class="co">#     xlim = c(0,50),</span></a>
<a class="sourceLine" id="cb47-9" data-line-number="9">     <span class="dt">main=</span><span class="st">&quot;Pays Capitalistes&quot;</span>,</a>
<a class="sourceLine" id="cb47-10" data-line-number="10">     <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>) </a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-15-2.png" width="672" /></p>
</div>
<div id="test-degalite-des-moyennes-bloctmi" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Test d’égalité des moyennes (BLOC*TMI)</h3>
<p>Maintenant que nous avons pris connaissance de la forme de nos deux variables BLOC et TMI, essayons de réaliser une opération statistique de plus haut niveau : le test d’une hypothèse. Nous savons grâce aux analyses précédentes que la mortalité infantile <em>semble</em> plus élévée en général dans les pays socialistes que dans les pays capitalistes. Mais pouvons nous le *prouver&quot; de façon rigoureuse en utilisant les règles de l’art ?</p>
<p>Bien évidemment, ce n’est pas l’apprentissage de R qui va vous apprendre la théorie des tests statistiques. Mais R va vous permettre très rapidement de mettre en oeuvre les tests que vous aurez appris en cours ou dans les manuels. Et surtout, il va vous offrir une gamme de possibilités de tests et de variantes qui devrait vous pousser à renforcer simultanément vos connaissances en R et en statitiques.</p>
<p>Dans l’exemple qui nous intéresse, les étudiants ayant une formation de base en statistique savent qu’il existe un test d’égalité des moyennes de deux échantillons appelé test t de student qui semble approprié au problème de comapraison de la mortalité infantile des pays socialistes et capitalistes. Il tient compte de l’effectif de ces échantillons (combiens de pays de chaque type ?) et de leur hétérogénéité interne (appelée variance). On devine intuitivement que la différence des moyennes de deux échantillons sera d’autant plus significative qu’elle oppose deux groupes homogènes comportant chacun de nombreux pays.</p>
<p>Si cela ne vous parait pas intuitif, imaginez un premier groupe de trois pays ayant pour mortalité (10, 20, 30) et un second groupe de trois pays également ayant pour mortalité (5,15,25). Leurs moyennes respectives sont 20 et 15, soit un écart de 5. Mais il semblerait hasardeux de conclure à de réelles différences compte tenu de l’étalement de chaque distribution.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1"><span class="co"># Comparaison de la distribution de deux échantillons</span></a>
<a class="sourceLine" id="cb48-2" data-line-number="2">VARQUANT&lt;-<span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">5</span>,<span class="dv">15</span>,<span class="dv">25</span>)</a>
<a class="sourceLine" id="cb48-3" data-line-number="3">VARQUALI&lt;-<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb48-4" data-line-number="4"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb48-5" data-line-number="5"><span class="kw">boxplot</span>(VARQUANT<span class="op">~</span><span class="st"> </span>VARQUALI)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Imaginez maintenant un premier groupe de 6 pays ayant pour mortalité (18,19,20,20,21,22) et un second groupe de 10 pays ayant pour mortalité (13,14,15,15,16,17). Les moyennes des deux groupes sont toujours respectivement de 20 et de 15, mais on “sent” que les écarts sont plus pertinents car ils portent sur deux groupes plus larges et surtout plus homogènes. Dit autrement, il est peu probable que les différences observées dans la seconde expérience soient le fruit du hasard alors que, dans le premier cas, on pouvait imaginer que les pays des deux groupes n’étaient pas fondamentalement différents.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1"><span class="co"># Comparaison de la distribution de deux échantillons</span></a>
<a class="sourceLine" id="cb49-2" data-line-number="2">VARQUANT&lt;-<span class="kw">c</span>(<span class="dv">18</span>,<span class="dv">19</span>,<span class="dv">20</span>,<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">13</span>,<span class="dv">14</span>,<span class="dv">15</span>,<span class="dv">15</span>,<span class="dv">16</span>,<span class="dv">17</span>)</a>
<a class="sourceLine" id="cb49-3" data-line-number="3">VARQUALI&lt;-<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb49-4" data-line-number="4"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb49-5" data-line-number="5"><span class="kw">boxplot</span>(VARQUANT<span class="op">~</span><span class="st"> </span>VARQUALI)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Le test T de student dont vous trouverez la formule dans tous les bons manuels va permettre de transformer l’intuition précédente en mesure objective et en donner une mesure fondamentale appelée <strong>p-value</strong> ou <em>seuil de rejet de l’hypothèse d’indépendance entre deux caractères</em>. Là encore, on peut donner une idée intuitive de ce qu’est la p-value en la présentant comme une mesure de la significativité de la relation entre deux caractères. De façon plus rigoureuse, la p-value mesure la probabilité que la relation observée entre deux variables (ici, la différence de moyenne) soit l’effet du hasard. La p-value varie entre 0 et 1, 0 signifiant que la significativité de la relation est certaine (la différence de moyenne ne peut pas être l’effet du hasard) et 1 signifiant qu’il n’existe aucune relation entre les deux variobles (les deux moyennes sont égales).</p>
<p>Examinons brièvement les valeurs de p-value sur nos deux exemples :</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="co"># Test paramétrique d&#39;égalité des moyennes de Student</span></a>
<a class="sourceLine" id="cb50-2" data-line-number="2">VARQUANT&lt;-<span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">5</span>,<span class="dv">15</span>,<span class="dv">25</span>)</a>
<a class="sourceLine" id="cb50-3" data-line-number="3">VARQUALI&lt;-<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb50-4" data-line-number="4"> <span class="kw">t.test</span>(VARQUANT <span class="op">~</span><span class="st"> </span>VARQUALI) </a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  VARQUANT by VARQUALI
## t = 0.61237, df = 4, p-value = 0.5734
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -17.66958  27.66958
## sample estimates:
## mean in group A mean in group B 
##              20              15</code></pre>
<p>Vous pouvez lire dans le résultat que la p-value est de 0.5734 ce qui signifie que l’on aurait 57% de chances de se tromper si l’on affirmait que la différence de moyenne entre les deux échantillons A et B est l’effet du hasard. Voyons ce qu’il en est pour notre second exemple</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1"><span class="co"># Test paramétrique d&#39;égalité des moyennes de Student</span></a>
<a class="sourceLine" id="cb52-2" data-line-number="2">VARQUANT&lt;-<span class="kw">c</span>(<span class="dv">18</span>,<span class="dv">19</span>,<span class="dv">20</span>,<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">22</span>,<span class="dv">13</span>,<span class="dv">14</span>,<span class="dv">15</span>,<span class="dv">15</span>,<span class="dv">16</span>,<span class="dv">17</span>)</a>
<a class="sourceLine" id="cb52-3" data-line-number="3">VARQUALI&lt;-<span class="kw">c</span>(<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;A&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>,<span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb52-4" data-line-number="4"><span class="kw">t.test</span>(VARQUANT <span class="op">~</span><span class="st"> </span>VARQUALI) </a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  VARQUANT by VARQUALI
## t = 6.1237, df = 10, p-value = 0.0001121
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  3.180732 6.819268
## sample estimates:
## mean in group A mean in group B 
##              20              15</code></pre>
<p>Cette fois-ci, vous pouvez voir que la valuer du t de student est beaucoup plus forte (6.13) ce qui se traduit par une p-value très proche de zéro (0.00011). La probabilité que les différences entre les deux échantillons soit l’effet du hasard est donc minime et on peut conclure avec une quasi-certiude que A et B correpondent à des groupes de pays ayant des mortalité significativement différentes.</p>
<p>Essayons maintenant d’appliquer ce même test de Student à notre exemple empirique de la mortalité infantile des pays socialistes et capitalistes.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="co"># Test paramétrique d&#39;égalité des moyennes de Student (inadapté)</span></a>
<a class="sourceLine" id="cb54-2" data-line-number="2"> <span class="kw">t.test</span>(euro<span class="op">$</span>TMI <span class="op">~</span><span class="st"> </span>euro<span class="op">$</span>BLOC) </a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  euro$TMI by euro$BLOC
## t = -3.1946, df = 7.3701, p-value = 0.01417
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -21.06338  -3.24912
## sample estimates:
## mean in group Cap mean in group Soc 
##           9.06875          21.22500</code></pre>
<p>Cette fois-ci le t de Student est égal à -3.19 et la p-value est égale à 0.0147, ce qui signifie que nous avons environ 1.5% de chances que les différences observées entre pays socialistes et capitalistes soient le simple effet du hasard et ne reflètent pas une véritable opposition. Du coup, que faut-il conclure ?</p>
<p>En sciences sociales, il est de tradition de considérer comme significatives les relations comportant un risque d’erreur inférieur à 5% soit 0.05. Puisque notre p-value est inférieure à 0.05, nous pouvons donc nous appuyer sur cette tradition et écrire que <em>“l’on peut affirmer avec un risque d’erreur inférieur à 5% que les pays socialistes et capitalistes présentaient des différences significatives de mortalité infantile en 1988”</em>.</p>
<p>Ou bien écrire plus simplement <em>“En 1988 en Europe, la mortalité infantile moyenne des pays socialistes (21.2 P.1000) était significativement plus forte que celles des pays capitalistes (9.1 p.1000)”</em> et ajouter dans une note en bas de page la remarque qui fait chic <em>p-value=0.0147</em>.</p>
<p>Ne concluez cependant pas trop vite que vous maitrisez désormais toutes les subtilités du test statistique d’égalité des moyennes. Si notre raisonnement précédent est <em>approximativement</em> juste, il serait sans doute critiqué par un vrai statisticien qui noterait immédiatement que le test t de student n’est pas le plus adapté à notre problème car (1) les distributions de mortalité ne sont pas gaussiennes et comportent des valeurs exceptionnelles comme l’Albanie pour les pays socialites ou le Portugal pour les pays capitalistes et (2) la variance des deux échantillons (leur hétérogénéité interne) n’est pas égale ce qui peut fausser l’usage du test de Student. Dans le cas présent, un bon statisticien préférerait sans doute utiliser un test non paramétrique, fondé sur la comparaison de l’ordre des observations et non pas leur valeur.</p>
<p>Soit par exemple le test de Wilcoxon, qu’il est très facile de mettre en oeuvre sour R en changeant à peine notre programme.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1"><span class="co"># Test non paramétrique d&#39;égalité des médianes de Wilcoxon (correct)</span></a>
<a class="sourceLine" id="cb56-2" data-line-number="2"> <span class="kw">wilcox.test</span>(euro<span class="op">$</span>TMI<span class="op">~</span>euro<span class="op">$</span>BLOC) </a></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test
## 
## data:  euro$TMI by euro$BLOC
## W = 8, p-value = 0.0001822
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>LA p-value est désormais égale à 0.0001 et on peut conclure avec certitude à l’existence de différence entre nos deux échantillons, ce qui n’était pas le cas avec le test de student, moins adapté au cas étudié.</p>
</div>
</div>
<div id="analyse-2-y-quanti-x-quanti" class="section level2">
<h2><span class="header-section-number">2.4</span> ANALYSE 2 (Y Quanti / X Quanti)</h2>
<p>La mortalité infantile (Y) peut-elle être estimée à l’aide du PIB/habitant (X) ?</p>
<p>Cette exemple de mise en relation de deux variables quantitatives permet de passer rapidement en revue les principe de base de l’analyse des corrélations entre plusieurs variables et de la réalisation d’un modèle d’ajustement linéaire. Il faut toutefois noter que l’exemple a surtout des vertus pédagogiques car le PNB/hab. des pays socialistes d’Europe en 1988 n’était pas véritablement connu et reposait sur des estimations.</p>
<div id="extraction-dune-matrice-a-partir-dun-tableau" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Extraction d’une matrice à partir d’un tableau</h3>
<p>Beaucoup de packages R ne sont pas adaptés au traitement tableau de données hétérogènes (type <strong>data.frame</strong>) mélangeant des variables qualitatives ou quantitatives. Il est donc souvent nécessaire d’extraire d’un tableau hétérogène les seuls variables quantitatives pour en faire un ensemble de lignes et de colonnes de nature homogène (type <strong>matrix</strong>). Cette matrice aura comme identifiant de colonnes le nom des variables (<strong>colnames</strong>) et il est pratique de lui ajouter comme nom de ligne l’identifiant des individus (<strong>rownames</strong>). Voici comment procéder :</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1">mat&lt;-<span class="kw">as.matrix</span>(euro[,<span class="kw">c</span>(<span class="st">&quot;TMI&quot;</span>,<span class="st">&quot;PNB&quot;</span>,<span class="st">&quot;URB&quot;</span>,<span class="st">&quot;FEC&quot;</span>,<span class="st">&quot;POP&quot;</span>)])</a>
<a class="sourceLine" id="cb58-2" data-line-number="2"><span class="kw">rownames</span>(mat)&lt;-euro<span class="op">$</span>PAYS</a>
<a class="sourceLine" id="cb58-3" data-line-number="3">mat</a></code></pre></div>
<pre><code>##      TMI   PNB URB FEC  POP
## ALB 43.0   600  34 3.3  3.1
## AUT 10.3 10000  55 1.4  7.6
## BEL  9.7  9200  95 1.5  9.9
## BUL 14.5  2000  65 2.0  9.0
## DAN  8.4 12600  84 1.5  5.1
## ESP  9.0  4800  91 1.7 39.0
## FIN  5.8 12200  62 1.6  4.9
## FRA  8.0 10100  73 1.8 55.9
## GRE 12.3  3700  58 1.7 10.1
## HON 19.0  2000  58 1.8 10.6
## IRL  8.7  5100  56 2.4  3.5
## ITA 10.1  8600  72 1.4 57.3
## NOR  8.5 15500  71 1.7  4.2
## PAY  7.7 10000  89 1.6 14.7
## POL 17.5  2100  61 2.2 38.0
## POR 15.8  2200  30 1.7 10.3
## RDA  9.2  3700  77 1.7 16.6
## RFA  8.6 12000  94 1.4 61.2
## ROU 25.6  1200  49 2.3 23.0
## ROY  9.5  8900  91 1.8 57.1
## SUE  5.9 13200  83 1.8  8.4
## SUI  6.8 17800  61 1.5  6.6
## TCH 13.9  3200  74 2.0 15.6
## YOU 27.1  2300  47 2.1 23.6</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1"><span class="kw">dim</span>(mat)</a></code></pre></div>
<pre><code>## [1] 24  5</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1"><span class="kw">str</span>(mat)</a></code></pre></div>
<pre><code>##  num [1:24, 1:5] 43 10.3 9.7 14.5 8.4 9 5.8 8 12.3 19 ...
##  - attr(*, &quot;dimnames&quot;)=List of 2
##   ..$ : chr [1:24] &quot;ALB&quot; &quot;AUT&quot; &quot;BEL&quot; &quot;BUL&quot; ...
##   ..$ : chr [1:5] &quot;TMI&quot; &quot;PNB&quot; &quot;URB&quot; &quot;FEC&quot; ...</code></pre>
</div>
<div id="calcul-des-correlations" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Calcul des corrélations</h3>
<p>La façon la plus simple de calculer un coefficient de corrélation est d’appliquerla fonction <em>cor</em> à une matrice :</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1"><span class="co"># Coefficients de corrélation de pearson</span></a>
<a class="sourceLine" id="cb64-2" data-line-number="2"><span class="kw">cor</span>(mat)</a></code></pre></div>
<pre><code>##            TMI         PNB        URB        FEC         POP
## TMI  1.0000000 -0.67645013 -0.6523693  0.8141417 -0.13586790
## PNB -0.6764501  1.00000000  0.4929530 -0.6045034  0.01784716
## URB -0.6523693  0.49295300  1.0000000 -0.5436824  0.39790430
## FEC  0.8141417 -0.60450337 -0.5436824  1.0000000 -0.20123367
## POP -0.1358679  0.01784716  0.3979043 -0.2012337  1.00000000</code></pre>
<p>R calcule par débaut le coefficient de corrélation linéaire de Bravais-Pearson qui varie entre -1 (corrélation négative parfaite) et +1 (corrélation positive parfaite). On peut ainsi voir que le taux de mortalité infantile (TMI) a une très forte corrélation positive avec l’indice conjonctuel de fécondité (+0.81) et une forte corrélation négative avec le PNB/hab (-0.68) ou le taux d’urbanisation (-0.65). La corrélationavec la population du pays est négative mais faible (-0.14).</p>
<p>Cette procédure n’est cependant pas totalement convaincante d’un point de vue statistique car elle n’affiche pas le degré de <em>significativité</em> de la liaison statistique, la fameuse <em>p-value</em> dont nous avons discuté dans l’exemple précédent. Cette significativité dépend en effet à la fois (1) de la valeur absolue du coefficient de corrélation (plus on se rapproche de +1 ou -1,plus la relation est significative) mais aussi (2) de la taille de l’échantillon utilisé pour calculer cette corrélation, appelée nombre de degrés de liberté. Lorsqu’on calcule un coefficient de corrélation, le nombre de dégré de liberté est égal à (N-2) c’est-àdire au nombre d’observations (N) moins le nombre de paramètres utilisés pour faire le calcul (soit 2, puisqu’on a besoin de la moyenne de X et de celle de Y).</p>
<p>On va donc plutôt faire appel à la procédure <em>rcorr</em> qui se trouve dans le package <strong>Hmisc</strong>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="co"># Coefficient de corrélation de Peason avec test de significativité</span></a>
<a class="sourceLine" id="cb66-2" data-line-number="2"><span class="kw">library</span>(Hmisc)</a>
<a class="sourceLine" id="cb66-3" data-line-number="3"><span class="kw">rcorr</span>(mat, <span class="dt">type=</span><span class="st">&quot;pearson&quot;</span>)</a></code></pre></div>
<pre><code>##       TMI   PNB   URB   FEC   POP
## TMI  1.00 -0.68 -0.65  0.81 -0.14
## PNB -0.68  1.00  0.49 -0.60  0.02
## URB -0.65  0.49  1.00 -0.54  0.40
## FEC  0.81 -0.60 -0.54  1.00 -0.20
## POP -0.14  0.02  0.40 -0.20  1.00
## 
## n= 24 
## 
## 
## P
##     TMI    PNB    URB    FEC    POP   
## TMI        0.0003 0.0006 0.0000 0.5267
## PNB 0.0003        0.0144 0.0018 0.9340
## URB 0.0006 0.0144        0.0060 0.0541
## FEC 0.0000 0.0018 0.0060        0.3457
## POP 0.5267 0.9340 0.0541 0.3457</code></pre>
<p>On voit ainsi apparaître deux tableaux, l’un avec les coefficients de corrélation des variables et l’autre avec les p-value associées à chacun de ces coefficients. Il apparaît alors que les corrélations du taux de mortalité infantile sont très significatives (&lt;0.001) avec le PNB/hab, le taux d’urbanisation et l’indice conjoncturel de fécondité. Mais que la corrélation entre mortalité infantile et population est non-significative.</p>
<p>Ajoutons maintenant une autre précaution statistique consistant à calculer un autre coefficient de corrélation, le coefficient de corrélation de rang aussi appelé coefficient de Spearman. L’intérêt de ce coefficient est tout d’abord de limiter le jeu des valeurs exceptionelles (<strong>outlier</strong>) qui sont liées à la position excentré d’une seule observation. Mais c’est aussi plus généralement de mettre en évidence des <strong>relations croissantes ou décroissantes de forme non-linéaire</strong> entre deux variables. En présence de ces deux types de singularité, le coefficient de Spearman affiche souvent des valeurs très divergentes de celui de Pearson. Et la découverte d’une discordance entre les deux coefficients est un indice à ne pas négliger.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1"><span class="co"># Coefficient de corrélation de Peason avec test de significativité</span></a>
<a class="sourceLine" id="cb68-2" data-line-number="2"><span class="kw">rcorr</span>(mat, <span class="dt">type=</span><span class="st">&quot;spearman&quot;</span>)</a></code></pre></div>
<pre><code>##       TMI   PNB   URB   FEC   POP
## TMI  1.00 -0.90 -0.57  0.51  0.17
## PNB -0.90  1.00  0.50 -0.65 -0.19
## URB -0.57  0.50  1.00 -0.44  0.35
## FEC  0.51 -0.65 -0.44  1.00 -0.07
## POP  0.17 -0.19  0.35 -0.07  1.00
## 
## n= 24 
## 
## 
## P
##     TMI    PNB    URB    FEC    POP   
## TMI        0.0000 0.0037 0.0113 0.4331
## PNB 0.0000        0.0124 0.0006 0.3859
## URB 0.0037 0.0124        0.0325 0.0917
## FEC 0.0113 0.0006 0.0325        0.7415
## POP 0.4331 0.3859 0.0917 0.7415</code></pre>
<p>Dans l’exemple (ancien mais pédagogique) qui a été choisi, il y a clairement une singularité dans la relation entre TMI et PNB puisque la corrélation qui était de (+0.68) avec le coefficient de Pearson grimpe à (+0.90) avec celui de Spearman. Dans le même temps, la relation entre TMI et FEC chute de (+0.81) à (+0.51) ce qui indique une autre singularité. Il faudra donc examinr soigneusement les nuages de points pour comprendre d’où viennent ces divergences, ce que l’on va faire au cours de l’étape suivante.</p>
</div>
<div id="visualisation-de-la-forme-de-la-relation-entre-deux-variables-quantitatives" class="section level3">
<h3><span class="header-section-number">2.4.3</span> Visualisation de la forme de la relation entre deux variables quantitatives</h3>
<p>On peut visualiser une relations entre deux variables X et Y à l’aide de l’instruction générique <em>plot()</em>. Soit par exemple la relation entre urbanisation et mortalité infantile :</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="kw">plot</span>(euro<span class="op">$</span>URB,euro<span class="op">$</span>TMI)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>On peut également ranger plusieurs graphiques en une seule figure en utilisant l’instruction générale <em>par</em> qui définit le format des graphiques, associée au paramètre <em>mfrow</em> qui indique combien de lignes et de colonnes on souhaite générer. Chacune des case de ce tableau servira successivement à afficher les graphiques demandés par l’instruction plot. Ici, nous déclarons que nous voulons ordonner les graphiques sur 2 lignes et 2 colonnes puis nous executons 4 fois de suite l’instruction plot.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" data-line-number="1"><span class="co"># Un seul graphique de synthèse</span></a>
<a class="sourceLine" id="cb71-2" data-line-number="2"><span class="kw">par</span>(<span class="dt">mfrow=</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)) </a>
<a class="sourceLine" id="cb71-3" data-line-number="3"><span class="kw">plot</span>(euro<span class="op">$</span>PNB,euro<span class="op">$</span>TMI)</a>
<a class="sourceLine" id="cb71-4" data-line-number="4"><span class="kw">plot</span>(euro<span class="op">$</span>URB,euro<span class="op">$</span>TMI)</a>
<a class="sourceLine" id="cb71-5" data-line-number="5"><span class="kw">plot</span>(euro<span class="op">$</span>FEC,euro<span class="op">$</span>TMI)</a>
<a class="sourceLine" id="cb71-6" data-line-number="6"><span class="kw">plot</span>(euro<span class="op">$</span>POP,euro<span class="op">$</span>TMI)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Ces figures permettent (avec un peu d’habitude …) d’expliquer les divergences observées entre les coefficients de corrélation de Pearson et de Spearman.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) </a>
<a class="sourceLine" id="cb72-2" data-line-number="2"></a>
<a class="sourceLine" id="cb72-3" data-line-number="3">X&lt;-euro<span class="op">$</span>PNB</a>
<a class="sourceLine" id="cb72-4" data-line-number="4">Y&lt;-euro<span class="op">$</span>TMI</a>
<a class="sourceLine" id="cb72-5" data-line-number="5"></a>
<a class="sourceLine" id="cb72-6" data-line-number="6">corlin&lt;-<span class="kw">round</span>(<span class="kw">cor</span>(X,Y),<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb72-7" data-line-number="7">reglin&lt;-<span class="kw">lm</span>(Y<span class="op">~</span>X)</a>
<a class="sourceLine" id="cb72-8" data-line-number="8"><span class="kw">plot</span>(X,Y, <span class="dt">main=</span><span class="kw">paste</span>(<span class="st">&quot;Coeff Pearson = &quot;</span>,corlin))</a>
<a class="sourceLine" id="cb72-9" data-line-number="9"><span class="kw">abline</span>(reglin,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb72-10" data-line-number="10"></a>
<a class="sourceLine" id="cb72-11" data-line-number="11">rankX&lt;-<span class="kw">rank</span>(X)</a>
<a class="sourceLine" id="cb72-12" data-line-number="12">rankY&lt;-<span class="kw">rank</span>(Y)</a>
<a class="sourceLine" id="cb72-13" data-line-number="13">corrank&lt;-<span class="kw">round</span>(<span class="kw">cor</span>(rankX,rankY),<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb72-14" data-line-number="14">regrank&lt;-<span class="kw">lm</span>(rankY<span class="op">~</span>rankX)</a>
<a class="sourceLine" id="cb72-15" data-line-number="15"><span class="kw">plot</span>(rankX,rankY, <span class="dt">main=</span><span class="kw">paste</span>(<span class="st">&quot;Coeff Spearman = &quot;</span>,corrank))</a>
<a class="sourceLine" id="cb72-16" data-line-number="16"><span class="kw">abline</span>(regrank,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<ul>
<li>la relation entre TMI et PNB est clairement non linéaire et forme un arc de parabole plutôt qu’une droite. C’est la raison pour laquelle le coefficient de Spearman était beaucoup plus élevé que celui de Pearson. En effet, lorsque l’on transforme les variables en rang, la courbure disparaît.</li>
</ul>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) </a>
<a class="sourceLine" id="cb73-2" data-line-number="2"></a>
<a class="sourceLine" id="cb73-3" data-line-number="3">X&lt;-euro<span class="op">$</span>FEC</a>
<a class="sourceLine" id="cb73-4" data-line-number="4">Y&lt;-euro<span class="op">$</span>TMI</a>
<a class="sourceLine" id="cb73-5" data-line-number="5"></a>
<a class="sourceLine" id="cb73-6" data-line-number="6">corlin&lt;-<span class="kw">round</span>(<span class="kw">cor</span>(X,Y),<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb73-7" data-line-number="7">reglin&lt;-<span class="kw">lm</span>(Y<span class="op">~</span>X)</a>
<a class="sourceLine" id="cb73-8" data-line-number="8"><span class="kw">plot</span>(X,Y, <span class="dt">main=</span><span class="kw">paste</span>(<span class="st">&quot;Coeff Pearson = &quot;</span>,corlin))</a>
<a class="sourceLine" id="cb73-9" data-line-number="9"><span class="kw">abline</span>(reglin,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb73-10" data-line-number="10"></a>
<a class="sourceLine" id="cb73-11" data-line-number="11">rankX&lt;-<span class="kw">rank</span>(X)</a>
<a class="sourceLine" id="cb73-12" data-line-number="12">rankY&lt;-<span class="kw">rank</span>(Y)</a>
<a class="sourceLine" id="cb73-13" data-line-number="13">corrank&lt;-<span class="kw">round</span>(<span class="kw">cor</span>(rankX,rankY),<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb73-14" data-line-number="14">regrank&lt;-<span class="kw">lm</span>(rankY<span class="op">~</span>rankX)</a>
<a class="sourceLine" id="cb73-15" data-line-number="15"><span class="kw">plot</span>(rankX,rankY, <span class="dt">main=</span><span class="kw">paste</span>(<span class="st">&quot;Coeff Spearman = &quot;</span>,corrank))</a>
<a class="sourceLine" id="cb73-16" data-line-number="16"><span class="kw">abline</span>(regrank,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<ul>
<li>la relation entre TMI et FEC est quant à elle influencée par une valeur exceptionnelle, l’Albanie, qui affiche une fécondité et une mortalité infantile excpetionnnelles. Le point Albanie est situé très en dehors du nuage des autres points et il fait fortement augmenter le coefficient de Pearson. Mais si l’on passe en rang, son effet disparaît et le nuage de point apparaît beaucoup moins linéaire, ce qui explique la valeur plus faible du coefficient de Spearman.</li>
</ul>
<p><strong>Le point important à retenir</strong> (en l’absence de la lecture d’un manuel de statistique plus précis) est qu’on ne doit pas tenter de faire passer une droite dans un nuage de points si celui-ci ne forme pas un ensemble de points régulièrement alignés. Il faut éviter d’utiliser la régression linéaire sur un nuage de points ayant une courbure ou sur un nuage de points comportant des valeurs exceptionnelles. On va voir dans la section suivante quelques “trucs” permettant de corriger la forme d’un nuage de point inadapté à une analyse de régression linéaire (ce qui ne dispense pas de lire un manuel de statistique expliquant ces trucs à l’aide des concepts plus précis d’autocorrélation des résidus, d’hétéroscédasticité, etc…)</p>
</div>
<div id="un-premier-modele-de-regression-lineaire-quick-dirty" class="section level3">
<h3><span class="header-section-number">2.4.4</span> Un premier modèle de régression linéaire (quick &amp; dirty …)</h3>
<p>Le calcul d’une régression linéaire se fait très facilement avec l’instruction <strong>lm</strong> qui est l’acronyme de <em>linear model</em>. La particularité de R par rapport à d’autres logiciels est de stocker les résultats d’une régression (et plus généralement d’un modèle statistique quelconque) dans un objet dont on choisit le nom (ici : <em>MonModele</em>). C’est objet est uen sorte de grand sac sans fonds contenant des dizaines de résultats que l’on peut sortir un par un en fonction de ses besoins et surtout de ses connaissances en statistiques… Les débutants se limiteront à demander de sortir du sac à malice un résumé (<em>summary</em>) de la régression qu’ils viennent d’opérer :</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1">MonModele &lt;-<span class="st"> </span><span class="kw">lm</span>(euro<span class="op">$</span>TMI<span class="op">~</span>euro<span class="op">$</span>PNB)</a>
<a class="sourceLine" id="cb74-2" data-line-number="2"><span class="kw">summary</span>(MonModele)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = euro$TMI ~ euro$PNB)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -7.921 -3.222 -1.440  1.064 22.344 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 21.3403638  2.3136443   9.224 5.14e-09 ***
## euro$PNB    -0.0011403  0.0002647  -4.308 0.000284 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.411 on 22 degrees of freedom
## Multiple R-squared:  0.4576, Adjusted R-squared:  0.4329 
## F-statistic: 18.56 on 1 and 22 DF,  p-value: 0.0002843</code></pre>
<p>On trouve dans ce résumé l’essentiel à savoir l’équation de la droite de régression linéaire dans la partie coefficient (TMI = -0.00114 * PNB + 21.34), le pouvoir explicatif du modèle qui est le carré du coefficient de corrélation appelé en anglais R-Squared (0.457 soit 46%) et la significativité générale du modèle qui est fournie par la p-value (0.00028). Cette dernière est en l’occurence conforme au coefficient de corrélation entre TMI et PNB car nous faisons une régression simple. On verra ultérieurement le cas des régressions multiples.</p>
<p>La visualisation de cette droite de régression peut se faire très simplement en traçant le nuage de point avec <strong>plot</strong> et en ajoutant la droite en utilisant l’instruction <strong>abline</strong> appliquée au sac à malice où se trouvent les résultats de notre modèle. Même si nous ignorons le contenu détaillé de ce sac, nous savons que R va y trouver les éléments utiles à savoir les coefficients de la droite de régression que nous avons déjà vu dans le résumé. On va faire un petit effort d’habillage en ajoutant à la figure un titre principal (<em>main</em>) et des titres d’axes (<em>xlab,ylab</em>).</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb76-2" data-line-number="2"><span class="kw">plot</span>(euro<span class="op">$</span>PNB,euro<span class="op">$</span>TMI,</a>
<a class="sourceLine" id="cb76-3" data-line-number="3">     <span class="dt">main=</span><span class="st">&quot; Richesse et mortalité infantile en Europe vers 1988&quot;</span>,</a>
<a class="sourceLine" id="cb76-4" data-line-number="4">     <span class="dt">ylab=</span><span class="st">&quot;PNB en $ par habitant (1988)&quot;</span>,</a>
<a class="sourceLine" id="cb76-5" data-line-number="5">     <span class="dt">xlab=</span><span class="st">&quot;Taux de mortalité infantile en p. 1000 (1988)&quot;</span>) </a>
<a class="sourceLine" id="cb76-6" data-line-number="6"><span class="kw">abline</span>(MonModele, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>Nous avons réussi à faire notre premier modèle de régression sous R ! Mais la vérité oblige à dire qu’il n’est pas satisfaisant puisque nous avons ajusté une droite dans un nuage de point qui est manifestement de forme non linéaire. Essayons de faire mieux, en montrant que la question statistique peut recouper des question plus théoriques de géographie économique et de géographie politique.</p>
</div>
<div id="un-deuxieme-modele-plus-satisfaisant-sur-le-plan-statistique-et-theorique" class="section level3">
<h3><span class="header-section-number">2.4.5</span> Un deuxième modèle plus satisfaisant sur le plan statistique et théorique</h3>
<p>La courbure de la relation entre PNB/habitant et taux de mortalité infantile est certes un problème statistique. Mais elle soulève aussi une question théorique plus intéressante : <em>Est-il raisonnable et logique de penser que plus le PNB/hab. augmente, plus la mortalité infantiel décroît de façon linéaire ?</em></p>
<p>Notre modèle précédent (Y=aX+b) est en partie absurde puisqu’il nous dit que la mortalité infantile minimale est de 21.34°/°° dans un pays ayant un PNB nul (on sait qu’il existe des mortalité infantile plus forte) et surtout il suppose que chaque fois que le PNB augmente de 1000 $, la mortalité infantile baisse de 1.1 °/°°. Du coup, ce modèle prévoit une absence totale de mortalité infantile pour les pays ayant un revenu supérieur à 15000 $/hab. Et il annonce froidement des <strong>mortalités infantile négatives</strong> au delà de ce niveau de richesse ! Bref, il y a une inconsistance logique dans un tel modèle, indépendamment du problème statistique de non linéarité.</p>
<p>Or, ce que nous disent les théoriciens du développement comme A. Sen est l’existence de rendements décroissant dans les progrès au fur et à mesure que la richesse augmente. En d’autres termes, la mortalité infantile diminue rapidement quant on passe de l’extrême apuvreté à la pauvreté. Mais ensuite elle baisse de moins en moins vite et son effet devient négligeable au delà d’un seuil de richesse. Le modèle correspondant à ces hypothèses théoriques est donc un modèle de décroissance non linéaire.</p>
<p>Il peut s’agir d’une loi exponentielle négative qui peut s’écrire Y = b.exp(-aX), ce que l’on peut transformer en équation linéaire en le réécrivant sous la forme log(Y) = log(b)+aX. Ou bien d’une loi puissance négative qui peut s’écrire Y = b.X^a et se transforme en équation linéaire log(y) = a.log(X)+log(b). Si l’on n’a pas de préférence théorique pour l’une ou l’autre de ces lois, on peut simplement examiner celle qui donne le meilleur ajustement linéaire après transformation logarithmique :</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) </a>
<a class="sourceLine" id="cb77-2" data-line-number="2"></a>
<a class="sourceLine" id="cb77-3" data-line-number="3">X&lt;-euro<span class="op">$</span>PNB</a>
<a class="sourceLine" id="cb77-4" data-line-number="4">Y&lt;-euro<span class="op">$</span>TMI</a>
<a class="sourceLine" id="cb77-5" data-line-number="5"></a>
<a class="sourceLine" id="cb77-6" data-line-number="6">corexp&lt;-<span class="kw">round</span>(<span class="kw">cor</span>(X,<span class="kw">log</span>(Y)),<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb77-7" data-line-number="7">regexp&lt;-<span class="kw">lm</span>(<span class="kw">log</span>(Y)<span class="op">~</span>X)</a>
<a class="sourceLine" id="cb77-8" data-line-number="8"><span class="kw">plot</span>(X,<span class="kw">log</span>(Y), <span class="dt">main=</span><span class="kw">paste</span>(<span class="st">&quot;Modèle exponentiel : r = &quot;</span>,corexp))</a>
<a class="sourceLine" id="cb77-9" data-line-number="9"><span class="kw">abline</span>(regexp,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb77-10" data-line-number="10"></a>
<a class="sourceLine" id="cb77-11" data-line-number="11">corpui&lt;-<span class="kw">round</span>(<span class="kw">cor</span>(<span class="kw">log</span>(X),<span class="kw">log</span>(Y)),<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb77-12" data-line-number="12">regpui&lt;-<span class="kw">lm</span>(<span class="kw">log</span>(Y)<span class="op">~</span><span class="kw">log</span>(X))</a>
<a class="sourceLine" id="cb77-13" data-line-number="13"><span class="kw">plot</span>(<span class="kw">log</span>(X),<span class="kw">log</span>(Y), <span class="dt">main=</span><span class="kw">paste</span>(<span class="st">&quot;Modèle puissance : r = &quot;</span>,corpui))</a>
<a class="sourceLine" id="cb77-14" data-line-number="14"><span class="kw">abline</span>(regpui,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>La comparaison des coefficients de corrélation mais aussi l’examen de la forme des nuages de points plaide clairement en faveur du choix du modèle puissance. Il demeure en effet une nette courbure du nuage de points dans le graphique du modèle exponentiel et l’ajustement obtenu est plus faible. Le modèle puissance affiche un alignement presque parfait des points avec une corrélation très élevée. Donc, <em>si l’on ne dispose pas d’arguments théoriques ou empiriques particuliers en faveur du modèle exponentiel</em>, on retiendra le modèle puissance pour modéliser la relation entre mortalité infantile et PNB/habitant des pays européens en 1988.</p>
</div>
<div id="un-troisieme-modele-la-revanche-des-pays-socialistes" class="section level3">
<h3><span class="header-section-number">2.4.6</span> Un troisième modèle : la revanche des pays socialistes …</h3>
<p>Comme nous savons désormais (1) que la mortalité infantile varie fortement entre les pays socialistes et capitalistes et (2) que la mortalité infantile dépend de la richesse par habitant, on peut proposer un dernier modèle qui va faire intervenir simultanément les variables. Il existe de nombreuses variantes pour construire un tel modèle que vous apprendrez dans les cours sur la régression multiple ou l’analyse multi-niveaux. On se limitera ici à une approche plus intuitive qui ne présuppose pas encore de connaître des techniques statistiques poussées.</p>
<p>Examinons tout d’abord la relation TMI*PNB dans les pays socialistes :</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb78-2" data-line-number="2"><span class="kw">summary</span>(euro<span class="op">$</span>PNB)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     600    2275    6850    7208   10575   17800</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" data-line-number="1">eurosoc&lt;-euro[euro<span class="op">$</span>BLOC<span class="op">==</span><span class="st">&quot;Soc&quot;</span>,]</a>
<a class="sourceLine" id="cb80-2" data-line-number="2">MonModele2soc &lt;-<span class="st"> </span><span class="kw">lm</span>(eurosoc<span class="op">$</span>TMI<span class="op">~</span>eurosoc<span class="op">$</span>PNB)</a>
<a class="sourceLine" id="cb80-3" data-line-number="3"><span class="kw">summary</span>(MonModele2soc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = eurosoc$TMI ~ eurosoc$PNB)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.9609 -4.0541 -0.7209  3.5026  7.9557 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 40.437252   5.552599   7.283 0.000341 ***
## eurosoc$PNB -0.008988   0.002383  -3.772 0.009271 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.25 on 6 degrees of freedom
## Multiple R-squared:  0.7033, Adjusted R-squared:  0.6539 
## F-statistic: 14.22 on 1 and 6 DF,  p-value: 0.009271</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" data-line-number="1"><span class="kw">plot</span>(eurosoc<span class="op">$</span>PNB,eurosoc<span class="op">$</span>TMI,</a>
<a class="sourceLine" id="cb82-2" data-line-number="2">                           <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">6000</span>),</a>
<a class="sourceLine" id="cb82-3" data-line-number="3">                            <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">50</span>),</a>
<a class="sourceLine" id="cb82-4" data-line-number="4">                           <span class="dt">main=</span><span class="st">&quot; Pays socialistes&quot;</span>,</a>
<a class="sourceLine" id="cb82-5" data-line-number="5">                           <span class="dt">ylab=</span><span class="st">&quot;PNB en $ par habitant (1988)&quot;</span>,</a>
<a class="sourceLine" id="cb82-6" data-line-number="6">                           <span class="dt">xlab=</span><span class="st">&quot;Taux de mortalité infantile en p. 1000 (1988)&quot;</span>) </a>
<a class="sourceLine" id="cb82-7" data-line-number="7"><span class="kw">abline</span>(MonModele2soc, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>La relation semble bien linéaire avec une valeur initiale forte de mortalité infantile (coefficient b=40.4) et une décroissance rapide de la mortalité infantile lorsque le PNB augmente (coefficient a = -0.009). La mortalité infantile baisse de 9 points chaque fois que le PNB augmente de 1000 $. On peut estimer qu’au delà d’un PNB de 5000 $ environ, la mortalité infantile n’existera plus dans les pays socialistes.</p>
<p>Examinons maintenant séparément la situation dans les pays capitalistes</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb83-2" data-line-number="2">eurocap&lt;-euro [euro<span class="op">$</span>BLOC<span class="op">==</span><span class="st">&quot;Cap&quot;</span>,]</a>
<a class="sourceLine" id="cb83-3" data-line-number="3">MonModele2cap &lt;-<span class="st"> </span><span class="kw">lm</span>(eurocap<span class="op">$</span>TMI<span class="op">~</span>eurocap<span class="op">$</span>PNB)</a>
<a class="sourceLine" id="cb83-4" data-line-number="4"><span class="kw">summary</span>(MonModele2cap)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = eurocap$TMI ~ eurocap$PNB)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.3212 -1.3747  0.4413  0.7973  3.5595 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.1654634  1.0987927  11.982 9.54e-09 ***
## eurocap$PNB -0.0004204  0.0001039  -4.048   0.0012 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.711 on 14 degrees of freedom
## Multiple R-squared:  0.5392, Adjusted R-squared:  0.5063 
## F-statistic: 16.38 on 1 and 14 DF,  p-value: 0.001199</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" data-line-number="1"><span class="kw">plot</span>(eurocap<span class="op">$</span>PNB,eurocap<span class="op">$</span>TMI,</a>
<a class="sourceLine" id="cb85-2" data-line-number="2">    <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">20000</span>),</a>
<a class="sourceLine" id="cb85-3" data-line-number="3">    <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">20</span>),</a>
<a class="sourceLine" id="cb85-4" data-line-number="4">     <span class="dt">main=</span><span class="st">&quot; Pays capitalistes&quot;</span>,</a>
<a class="sourceLine" id="cb85-5" data-line-number="5">     <span class="dt">ylab=</span><span class="st">&quot;PNB en $ par habitant (1988)&quot;</span>,</a>
<a class="sourceLine" id="cb85-6" data-line-number="6">     <span class="dt">xlab=</span><span class="st">&quot;Taux de mortalité infantile en p. 1000 (1988)&quot;</span>) </a>
<a class="sourceLine" id="cb85-7" data-line-number="7"><span class="kw">abline</span>(MonModele2cap, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>La relation semble à nouveauà peu près linéaire. La valeur initiale de mortalité infantile est plus faible que dans les pays socialistes (coefficient a = 13.1) mais ensuite la décroissance est lente lorsque le PNB augmente (coefficient a = -0.0004). La mortalité infantile ne baisse que de 0.4 points lorsque le PNB augmente de 1000 $. Il faudrait donc un PNB d’environ 30000 $ par habitant pour que la mortalité infantile disparaissent dans les pays capitalistes, alors qu’il suffisant de 5000 $ par habitant dans les pays socialistes !</p>
<p>On va résumer ce dernier modèle par une seule figure sur laquelle on affichera simultanément les deux droites de régression.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb86-2" data-line-number="2"></a>
<a class="sourceLine" id="cb86-3" data-line-number="3"><span class="kw">plot</span>(euro<span class="op">$</span>PNB,euro<span class="op">$</span>TMI,</a>
<a class="sourceLine" id="cb86-4" data-line-number="4">    <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">20000</span>),</a>
<a class="sourceLine" id="cb86-5" data-line-number="5">    <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">50</span>),</a>
<a class="sourceLine" id="cb86-6" data-line-number="6">     <span class="dt">main=</span><span class="st">&quot;Influence du niveau de vie et du syème politique sur la mortalité infantile&quot;</span>,</a>
<a class="sourceLine" id="cb86-7" data-line-number="7">     <span class="dt">xlab=</span><span class="st">&quot;PNB en $ par habitant (1988)&quot;</span>,</a>
<a class="sourceLine" id="cb86-8" data-line-number="8">     <span class="dt">ylab=</span><span class="st">&quot;Taux de mortalité infantile en p. 1000 (1988)&quot;</span>) </a>
<a class="sourceLine" id="cb86-9" data-line-number="9"></a>
<a class="sourceLine" id="cb86-10" data-line-number="10"><span class="kw">points</span>(eurosoc<span class="op">$</span>PNB,eurosoc<span class="op">$</span>TMI,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb86-11" data-line-number="11"><span class="kw">text</span>(eurosoc<span class="op">$</span>PNB,eurosoc<span class="op">$</span>TMI,eurosoc<span class="op">$</span>PAYS,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">cex=</span><span class="fl">0.5</span>,<span class="dt">pos=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb86-12" data-line-number="12"><span class="kw">abline</span>(MonModele2soc,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb86-13" data-line-number="13"></a>
<a class="sourceLine" id="cb86-14" data-line-number="14"><span class="kw">points</span>(eurocap<span class="op">$</span>PNB,eurocap<span class="op">$</span>TMI,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb86-15" data-line-number="15"><span class="kw">text</span>(eurocap<span class="op">$</span>PNB,eurocap<span class="op">$</span>TMI,eurocap<span class="op">$</span>PAYS,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">cex=</span><span class="fl">0.5</span>,<span class="dt">pos=</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb86-16" data-line-number="16"><span class="kw">abline</span>(MonModele2cap,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<p><img src="StatR_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>Selon ce modèle, on pouvait penser en 1988 qu’un pays capitaliste comme le Portugal devrait très fortementaccroître son PNB par habitant pour voir baisser sa mortalité infantile. Inversement, la Pologne qui était un pays socialiste aurait du voir rapidement sa situation s’améliorer, pour peu qu’elle accroisse légèrement son PNB/habitant. Mais on ne saura jamais si le modèle aurait été vérifié puisque le bloc socialiste s’est dissous en 1989 …</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="un-tableau-de-donnes-denquete-les-menages-de-yemessoa-en-2005.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01-quanti.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["StatR.pdf", "StatR.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
